### ISSUE TITLE
Can we have middleware to support custom load-balancing? 

### ISSUE THREAD

**Issue by MrSpark2591** [h2non/rocky#109]
Currently only .balance([server array]) takes care of load balancing and it's Round robin way of load balancing. What if I want to divide request load to server let's say 70% and 30% (assuming only two instances are running) depending on the health of the server. 

So the feature I want is to have .balanceFunction(<pass some function>) and where we can add custom code for load balancing.

Thank you.

**Comment by tomas-fp** [comment]
Yes, you can write your custom middleware that does this for you.

You can simply use something like this:
```
proxy.use(function (req, res, next) {
  const urls = ['http://server1', 'http://server2']
  const target = urls[Math.random() > 0.3 ? 0 : 1]
  req.rocky.opts.target = target
  next()
})
```

**Comment by MrSpark2591** [comment]
@tomas-fp Thank you so much :)

**Comment by tomas-fp** [comment]
Just do the same at route level (which also implements a middleware extensible interface):
```js
proxy.all('/service1').use(function myCustomBalancer (req, res, next) {
  const urls = ['http://server1', 'http://server2']
  const target = urls[Math.random() > 0.3 ? 0 : 1]
  req.rocky.options.target = target
  next()
})
```
