### ISSUE TITLE
custom load balancer support 

### ISSUE THREAD

**Issue by MrSpark2591** [h2non/rocky#111]
For now, round robin is used for load balancing servers. Can we have option where we can pass a function and it will override default load balancing.
something like this
```
var someFunction() = function(){
//logic for load balancing
return //target server url;
} 
proxy 
  .balancer(someFunction())

```

**Comment by h2non** [comment]
See: https://github.com/h2non/rocky/issues/107

**Comment by h2non** [comment]
See: https://github.com/h2non/rocky/issues/109#issuecomment-301717480

**Comment by h2non** [comment]
You should simply your own middleware function responsible of performing the custom balancing.

**Comment by MrSpark2591** [comment]
yes, but it will not override balance method :) so why to perform round robin when you actually don't need it. hope you understand 👍

**Comment by h2non** [comment]
No. Just forget about the balance method and built-in implementation. Just use your custom implementation. Makes sense?
