### ISSUE TITLE
How to access upstream response's statusCode in response middleware callbacks?

### ISSUE THREAD

**Issue by h6ah4i** [h2non/rocky#113]
Hi. Thanks for the superb library, it's very handy and useful! However, I am just struggling the behavior of `useResponse()` callback now.

### What I want to do

I want to change the response body according to `statusCode` of upstream. However, the `res.statusCode` is always 200 in `useResponse` callbacks. Is this intended behavior?

```javascript
proxy
   .get('/:filename')
   .useResponse((req, res, next) => {
     if (res.statusCode == 200) {  // <-- res.statusCode is always 200
       res.body = "xxx";
     } else {
       res.body = "yyy";
     }
     ...
   }

```

### Hack

I dug into the rocky library and found that the `headArgs` variable holds the original status code which I need. I tweaked the `lib/middleware/response-body.js` like following;

```diff
    res.end = function (data, encoding) {
      ...

      // Restore native methods
      restore()

+     if (headArgs) {
+       res.statusCode = headArgs[0];
+     }

      // Trigger response middleware stack
      middleware(req, res, partial(finisher, cb))
    }
```

I am not sure whether this modification is good or bad, so I've not created a pull request yet :(

Thanks.

**Comment by h2non** [comment]
Wow. I suspect this is a change in nodejs internals in latest versions. I don't know why that happens, the `statusCode` property should be defined when calling `response.writeHead()` method :S

Anyway, I have fixed this. Try upgrading `rocky` to `v0.4.15`:
```bash
$ npm update rocky
```

Thanks for reporting the issue.

**Comment by h6ah4i** [comment]
Thanks for a quick response 😄
