### ISSUE TITLE
removeHeader from useResponse middleware causes the wrong statusCode to be sent

### ISSUE THREAD

**Issue by robholland** [h2non/rocky#71]
Hey, I've tried to figure out what's going wrong here but I've not been able to.

```
var rocky = require('rocky');
var http = require('http');

// Target server
http.createServer(function (req, res) {
  res.writeHead(301, { Location: 'http://somewhereelse/'})
  res.end()
}).listen(3000)

var proxy = rocky()

proxy.all('/simple')
     .forward('http://localhost:3000')

proxy.all('/response')
     .useResponse(function(req, res, next) {
       res.removeHeader('foo')
       next()
     })
     .forward('http://localhost:3000')

proxy.listen(3001)

// Test request
http.get('http://localhost:3001/simple', function (res) {
  console.log('Status:', res.statusCode)
})

http.get('http://localhost:3001/response', function (res) {
  console.log('Status:', res.statusCode)
})
```

This test prints:

Status: 301
Status: 200

The response status should always be 301, but for some reason if I call res.removeHeader using useResponse middleware the status code returned is 200 rather than the expected 301. My guess is that  the default 200 status is being written, but I can't see what's triggering that. Node's removeHeader method doesn't force writeHead be called that I can see.

Happy to work on fixing this more but I'm not sure where to look/what to try next.

**Comment by h2non** [comment]
I've just fixed the issue. Actually, it was a bit particular. As you supposed, `http.IncomingMessage` has a default status code of `200`. The problem was that `writeHead()` call arguments aren't properly cached due to bad `Arguments` object to `Array` conversion. This makes impossible to pass the proper status code and headers in the original call to `writeHead()`.

I've released a fresh version with the fix, so feel free to update your tree and try it again:
```js
var rocky = require('rocky')
var http = require('http')

// Target server
http.createServer(function (req, res) {
  res.writeHead(301, { Location: 'http://somewhereelse/', foo: 'bar' })
  res.end()
}).listen(3000)

var proxy = rocky()

proxy.all('/simple')
  .forward('http://localhost:3000')

proxy.all('/response')
  .useResponse(function (req, res, next) {
    res.removeHeader('foo')
    next()
  })
  .forward('http://localhost:3000')

proxy.listen(3001)

// Test request
http.get('http://localhost:3001/simple', function (res) {
  console.log('Status:', res.statusCode)
  console.log('Foo header:', res.headers.foo)
})

http.get('http://localhost:3001/response', function (res) {
  console.log('Status:', res.statusCode)
  console.log('Foo header:', res.headers.foo)
})
```

Thanks for reporting!
