### ISSUE TITLE
Try to set rocky between pouchdb and couchdb with no success

### ISSUE THREAD

**Issue by mfilotto** [h2non/rocky#87]
Hi,
I try to add a proxy between pouchdb and couchdb with no luck.
I have this error : `TypeError: Invalid non-string/buffer chunk`
Have you ever try such a config ?
Thanks
Mathieu

**Comment by h2non** [comment]
That's strange. That type error is throwed by node.js stream internals. See: 
https://github.com/nodejs/node/blob/cc0342a517279c9c52543e3a37e11da3fc6cdb36/lib/_stream_writable.js#L165-L184

Are you using some response middleware/interceptor? Can you share some code?

**Comment by mfilotto** [comment]
Here is my code :
```
var rocky = require('rocky');
var express = require('express');
var bodyParser = require('body-parser');
var cors = require('cors');
var path = require('path');
var compress = require('compression');

var proxy = rocky();
var app = express();
var oneMonth = 2628000000;
var corsOptions = {
    credentials: true,
    origin: 'http://localhost:3000'
};

app.set('port', process.env.PORT || 3010);
app.use(compress());
app.use(cors(corsOptions));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(express.static(path.join(__dirname, 'public'), { maxAge: oneMonth }));

proxy.all("/sites/*")
     .forward('http://couch.spotearth.nc');

app.use(proxy.middleware())

app.listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
});
```
I really appreciate your help, thanks !

**Comment by h2non** [comment]
Try removing the body parser middleware. I believe you don't need for that scenario.

Do you know that you can use rocky without express? You can also try using it in raw mode.

**Comment by mfilotto** [comment]
I also have a bunch of endpoints that I removed from the code I sent

**Comment by mfilotto** [comment]
I try to isolate each part, so I try to use rocky in raw mode. 
But now I have a cors issue, how can I manage cors with rocky ?

**Comment by mfilotto** [comment]
So my code is now
```js
var rocky = require('rocky');
var proxy = rocky();

proxy.all("/db/*")
     .forward('http://my.couchdb.server');

proxy.listen(3010, function () {});
```

**Comment by h2non** [comment]
Try using the [cors](https://github.com/expressjs/cors) middleware directly as `rocky` middleware. It should work with raw node.js `http.IncomingMessage` interface.
 
```js
proxy.use(cors({
    credentials: true,
    origin: 'http://localhost:3000'
}))
```

**Comment by mfilotto** [comment]
OK pass though the cors issue
Now I have a 502 bad gateway

**Comment by h2non** [comment]
That's an issue while routing the traffic. Are you sure that the HTTP path is correctly configured to be forwarded to another server?

**Comment by mfilotto** [comment]
oops you're right.
Now I have a 503

**Comment by h2non** [comment]
That's an issue while resolving the hostname or network dialing error. Please, verify the server you want to forward is accessible via network.

**Comment by mfilotto** [comment]
Ouch you're right, the hostname is not a real one, I just add it in my hosts

**Comment by h2non** [comment]
> Is there a way to have the same with rocky?
Can you explain this a bit...?

**Comment by mfilotto** [comment]
Can rocky (or another node middleware) can use custom DNS rules provided:
- either through the /ect/hosts file of the OS on which node is running
- or programmatically defined
My need is probably a node dns proxy

**Comment by h2non** [comment]
You can simply use a custom NS to resolve hostnames. You can do that programmatically. See [dns](https://nodejs.org/api/dns.html) native module. 

I'm going to close this issue since it's the stuff discussed here is outside of the scope of `rocky`.

**Comment by mfilotto** [comment]
Thanks for your help.
I really appreciate
